# Generated by Django 2.2 on 2019-04-25 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('region', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, null=True)),
            ],
            options={
                'unique_together': {('name', 'region')},
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Use',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('imo', models.PositiveIntegerField(blank=True, null=True, verbose_name='IMO Number')),
                ('fleetmon', models.PositiveIntegerField(blank=True, null=True, verbose_name='FleetMon ID')),
                ('year_built', models.PositiveSmallIntegerField(verbose_name='Year Built')),
                ('tonnage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Gross Tonnage')),
                ('length', models.FloatField(blank=True, null=True, verbose_name='Length (m)')),
                ('beam', models.FloatField(blank=True, null=True, verbose_name='Beam (m)')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('former_names', models.TextField(blank=True, verbose_name='Former Names')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('slug', models.SlugField(max_length=205, null=True, verbose_name='Slug')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atlas.City', verbose_name='Location - City')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atlas.Country', verbose_name='Location - Country')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atlas.Owner', verbose_name='Owner')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='atlas.Status', verbose_name='Current Status')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='atlas.Type', verbose_name='Type of Ship')),
                ('uses', models.ManyToManyField(blank=True, to='atlas.Use', verbose_name='Current Use(s)')),
            ],
        ),
    ]
