# Generated by Django 2.2 on 2019-05-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='fleetmon',
        ),
        migrations.AlterField(
            model_name='ship',
            name='slug',
            field=models.SlugField(max_length=200, null=True, verbose_name='Slug'),
        ),
    ]
