# Generated by Django 2.2 on 2019-05-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0002_auto_20190501_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
            preserve_default=False,
        ),
    ]
